
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftCOMPUNIONINTERSECTDIFFERENCECOMP COPROJ DI DIFFERENCE ID INTERSECT INV LPAREN NUMBER PROJ RELATION RPAREN TRANS UNIONexpression : RELATIONexpression : expression COMP expressionexpression : IDexpression : DIexpression : PROJ NUMBER LPAREN expression RPARENexpression : INV LPAREN expression RPARENexpression : expression INTERSECT expressionexpression : expression UNION expressionexpression : expression DIFFERENCE expressionexpression : COPROJ NUMBER LPAREN expression RPARENexpression : TRANS LPAREN expression RPARENexpression : LPAREN expression RPAREN'
    
_lr_action_items = {'RELATION':([0,6,10,11,12,13,16,18,23,26,],[2,2,2,2,2,2,2,2,2,2,]),'ID':([0,6,10,11,12,13,16,18,23,26,],[3,3,3,3,3,3,3,3,3,3,]),'DI':([0,6,10,11,12,13,16,18,23,26,],[4,4,4,4,4,4,4,4,4,4,]),'PROJ':([0,6,10,11,12,13,16,18,23,26,],[5,5,5,5,5,5,5,5,5,5,]),'INV':([0,6,10,11,12,13,16,18,23,26,],[7,7,7,7,7,7,7,7,7,7,]),'COPROJ':([0,6,10,11,12,13,16,18,23,26,],[8,8,8,8,8,8,8,8,8,8,]),'TRANS':([0,6,10,11,12,13,16,18,23,26,],[9,9,9,9,9,9,9,9,9,9,]),'LPAREN':([0,6,7,9,10,11,12,13,14,16,17,18,23,26,],[6,6,16,18,6,6,6,6,23,6,26,6,6,6,]),'$end':([1,2,3,4,19,20,21,22,24,29,31,32,33,],[0,-1,-3,-4,-2,-7,-8,-9,-12,-6,-11,-5,-10,]),'COMP':([1,2,3,4,15,19,20,21,22,24,25,27,28,29,30,31,32,33,],[10,-1,-3,-4,10,-2,-7,-8,-9,-12,10,10,10,-6,10,-11,-5,-10,]),'INTERSECT':([1,2,3,4,15,19,20,21,22,24,25,27,28,29,30,31,32,33,],[11,-1,-3,-4,11,-2,-7,-8,-9,-12,11,11,11,-6,11,-11,-5,-10,]),'UNION':([1,2,3,4,15,19,20,21,22,24,25,27,28,29,30,31,32,33,],[12,-1,-3,-4,12,-2,-7,-8,-9,-12,12,12,12,-6,12,-11,-5,-10,]),'DIFFERENCE':([1,2,3,4,15,19,20,21,22,24,25,27,28,29,30,31,32,33,],[13,-1,-3,-4,13,-2,-7,-8,-9,-12,13,13,13,-6,13,-11,-5,-10,]),'RPAREN':([2,3,4,15,19,20,21,22,24,25,27,28,29,30,31,32,33,],[-1,-3,-4,24,-2,-7,-8,-9,-12,29,31,32,-6,33,-11,-5,-10,]),'NUMBER':([5,8,],[14,17,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,6,10,11,12,13,16,18,23,26,],[1,15,19,20,21,22,25,27,28,30,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> RELATION','expression',1,'p_expression_R','rcyacc.py',89),
  ('expression -> expression COMP expression','expression',3,'p_expression_comp','rcyacc.py',98),
  ('expression -> ID','expression',1,'p_expression_ID','rcyacc.py',110),
  ('expression -> DI','expression',1,'p_expression_DI','rcyacc.py',118),
  ('expression -> PROJ NUMBER LPAREN expression RPAREN','expression',5,'p_expression_proj','rcyacc.py',129),
  ('expression -> INV LPAREN expression RPAREN','expression',4,'p_expression_inv','rcyacc.py',138),
  ('expression -> expression INTERSECT expression','expression',3,'p_expression_intersect','rcyacc.py',144),
  ('expression -> expression UNION expression','expression',3,'p_expression_union','rcyacc.py',158),
  ('expression -> expression DIFFERENCE expression','expression',3,'p_expression_difference','rcyacc.py',175),
  ('expression -> COPROJ NUMBER LPAREN expression RPAREN','expression',5,'p_expression_coproj','rcyacc.py',190),
  ('expression -> TRANS LPAREN expression RPAREN','expression',4,'p_expression_trans','rcyacc.py',205),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_parenth','rcyacc.py',215),
]
